# Instructions ----
#' This file follows the format generated by FIMS:::use_testthat_template().
#' Necessary tests include input and output (IO) correctness [IO
#' correctness], edge-case handling [Edge handling], and built-in errors and
#' warnings [Error handling]. See `?FIMS:::use_testthat_template` for more
#' information. Every test should have a @description tag, which can only span
#' one lines, that will be used in the bookdown report of the results from
#' {testthat}. This line can be more than 80 characters.

# create_default_* ----
## Setup ----
data <- FIMS::FIMSFrame(data_big)

default_model <- fims_model(data) |>
  fims_growth() |>
  fims_recruitment() |>
  fims_maturity() |>
  fims_observations(fleet = "fleet1") |>
  fims_observations(fleet = "survey1")

default_parameter_plan <- build_fims_model_parameter_plan(default_model)

# create_default_parameters ----
## IO correctness ----
test_that("`create_default_parameters()` works with correct inputs", {
  result <- create_default_parameters(
    parameter_plan = default_parameter_plan,
    data = data
  )
  result_unnested <- result |>
    tidyr::unnest(cols = data)

  #' @description Test that the main output is a `tbl_df`.
  expect_s3_class(result, "tbl_df")
  #' @description Test that the main output table has the correct column structure.
  expect_equal(
    colnames(result),
    c("model_family", "module_name", "fleet_name", "data")
  )
  #' @description Test that the `data` column is structured to hold nested information.
  expect_true(is.list(result[["data"]]))
  #' @description Test that the nested information within the `data` column is also a `tbl_df`.
  expect_s3_class(result[["data"]][[1]], "tbl_df")
  #' @description Test that the nested data table has the correct column structure.
  expect_equal(
    colnames(result[["data"]][[1]]),
    c(
      "module_type", "label", "age", "length", "time",
      "value", "estimation_type", "distribution_type", "distribution"
    )
  )
  #' @description Test that the generated parameter values have not changed from the accepted snapshot.
  expect_snapshot_file(
    save_csv(result_unnested),
    "default_parameters.csv",
    compare = compare_file_text
  )
})

## Edge handling ----
test_that("`create_default_parameters()` works with edge cases", {
  # Set up a model without a distribution for recruitment, which should lead to
  # `log_devs` having an estimation_type of "constant" and no `log_sd` parameter
  # being created.
  updated_parameter_plan <- fims_model(data) |>
    fims_growth() |>
    fims_recruitment(process_distribution = NA_character_) |>
    fims_maturity() |>
    fims_observations(fleet = "fleet1") |>
    fims_observations(fleet = "survey1") |>
    build_fims_model_parameter_plan()
  result <- create_default_parameters(
    parameter_plan = updated_parameter_plan,
    data = data
  )

  #' @description Test that `log_sd` has not been set up when distribution is not specified.
  expect_equal(
    result |>
      tidyr::unnest(cols = data) |>
      dplyr::filter(module_name == "Recruitment", label == "log_sd") |>
      dplyr::pull(value),
    numeric(0)
  )

  #' @description Test that the `log_devs` estimation_type is set to "constant" when distribution is not specified.
  expect_equal(
    result |>
      tidyr::unnest(cols = data) |>
      dplyr::filter(module_name == "Recruitment", label == "log_devs") |>
      dplyr::pull(estimation_type),
    rep("constant", result |>
      tidyr::unnest(cols = data) |>
      dplyr::filter(module_name == "Recruitment", label == "log_devs") |>
      nrow())
  )
})

## Error handling ----
# No built-in errors to test.

# TODO: Add additional tests for internal (unexposed) functions,
# such as create_default_population().
